---
title: "Reference data"
author: "Andrey Vladimirov"
date: "`r format(Sys.Date(), '%b %d %y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**General info**:

The data in the file 'Data_Vladimirov.csv' are socio-economic indicators for 2015-2016 years.
Objective of this lab: Analyze data using the R language and report using R Markdown package.

**Variable notation**:

*   Regions - full list of the Russian Federation region;

*   Federal district - federal district of the region;

*   Y - retail trade turnover per capita in 2016;

*   X1 - the number of small businesses per 10000 people in 2016;

*   X2 - the use of information and communication technologies in organizations: personal computers in 2016;

*   X3 - expenditures of the consolidated budgets of the constituent entities of the Russian Federation: total in 2015;

*   X4 - real cash income of the population in 2016.

**Source**:
1. Regions of Russia. Socio-economic indicators 2017: https://rosstat.gov.ru/storage/mediabank/peg-pok17.pdf
2. Regions of Russia. Socio-economic indicators 2018: https://rosstat.gov.ru/storage/mediabank/Reg-pok18.pdf